version: '3'
services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j-barista
    restart: unless-stopped
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/QsRntifUFPQjvt2Q8AG
      - NEO4JLABS_PLUGINS=["apoc", "graph-data-science"]
