name: Validate pull request

on: [pull_request]

jobs:
  run:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
    env:
        CI: true
    steps:
    - uses: actions/checkout@v2
    - name: Validate pull request
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn install --frozen-lockfile
    - run: yarn lint
    - run: yarn test
